name: "Build FreeRTOS demo and compare sizes"

on: [push]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
    contents: read
    pages: write
    id-token: write


# Allow only one concurrent deployment, skipping runs queued between the
# run in-progress and latest queued.  However, do NOT cancel in-progress
# runs as we want to allow these production deployments to complete.
concurrency:
    group: "pages"
    cancel-in-progress: false

jobs:
    compare:
        runs-on: "ubuntu-latest"

        steps:
            - name: "GitHub: Checkout Repository"
              uses: "actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8" #v5.0.0
              with:
                  submodules: true

            - name: "GitHub: Setup Nix"
              # IMPORTANT:
              # Consider GitHub Actions Pinning for additional security.
              # See: https://stackoverflow.com/a/78905195
              uses: "custom-workflows/setup-nix@d3dc49dd7bd37d10de81c938bebefad918e4d499"
              with:
                # NOTE:
                # Set 'nix_path' by:
                #  - Picking a channel → https://status.nixos.org/
                #  - Pin 'nixpkgs' → https://nix.dev/reference/pinning-nixpkgs
                nix_path: nixpkgs=channel:nixos-unstable

            - name: "Nix: Build"
              run: |
                nix develop -c bash -c "cd FreeRTOS-Demo && make compare"

            - name: Upload artifact
              uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b #v4
              if: ${{ github.ref == 'refs/heads/main' }}
              with:
                  # Upload entire repository
                  path: 'FreeRTOS-Demo/misc/'

            - name: Deploy to GitHub Pages
              if: ${{ github.ref == 'refs/heads/main' }}
              id: deployment
              uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e #v4
